{% set name = "sentence-transformers" %}
{% set version = "5.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/UKPLab/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 3b2bc42eb63f08fef4684c1829c5c903e28108b64134c2c14258a1206c093b10

build:
  skip: True  # [py<310]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - wheel
    - setuptools >=42
  run:
    - python
    - transformers >=4.41.0,<6.0.0
    - tqdm
    - pytorch >=1.11.0
    - scikit-learn
    - scipy
    - huggingface_hub >=0.20.0
    - typing_extensions >=4.5.0
  run_constrained:
    - huggingface_accelerate >=0.20.3

# E  TypeError: Cannot convert a MPS Tensor to float64 dtype as the MPS framework doesn't support float64. Please use float32 instead.
{% set skip_tests_osx = "test_dense_load_and_save_in_other_precisions" %}  # [osx]
# There is not full support for MPS in Pytorch: NotImplementedError: Could not run 'aten::_sparse_coo_tensor_with_dims_and_tensors' with arguments from the 'SparseMPS' backend.
{% set skip_tests_osx = skip_tests_osx + " or test_decode_shapes" %}  # [osx]
{% set skip_tests_osx = skip_tests_osx + " or test_decode_token_types" %}  # [osx]
{% set skip_tests_osx = skip_tests_osx + " or test_decode_top_k_respects_limit" %}  # [osx]
{% set skip_tests_osx = skip_tests_osx + " or test_decode_handles_sparse_dense_inputs" %}  # [osx]
{% set skip_tests_osx = skip_tests_osx + " or test_decode_returns_sorted_weights" %}  # [osx]
{% set skip_tests_osx = skip_tests_osx + " or test_inference_free_splade" %}  # [osx]
{% set skip_tests_osx = skip_tests_osx + " or test_encode_query_document_vs_encode" %}  # [osx]
{% set skip_tests_osx = skip_tests_osx + " or test_default_prompt" %}  # [osx]
{% set skip_tests_osx = skip_tests_osx + " or test_sparsity" %}  # [osx]
{% set skip_tests_osx = skip_tests_osx + " or test_intersection" %}  # [osx]
{% set skip_tests_osx = skip_tests_osx + " or test_encode_with_dataset_column" %}  # [osx]
{% set skip_tests_osx = skip_tests_osx + " or test_empty_encode" %}  # [osx]
{% set skip_tests_osx = skip_tests_osx + " or test_get_model_kwargs" %}  # [osx]
{% set skip_tests_osx = skip_tests_osx + " or test_sparse_static_embedding_padding_ignored" %}  # [osx]
{% set skip_tests_osx = skip_tests_osx + " or test_sparse_static_embedding_save_load" %}  # [osx]
{% set skip_tests_osx = skip_tests_osx + " or test_opensearch_v2_distill_similarity" %}  # [osx]
{% set skip_tests_osx = skip_tests_osx + " or test_opensearch_v3_distill_similarity" %}  # [osx]
{% set skip_tests_osx = skip_tests_osx + " or test_load_and_encode" %}  # [osx]
{% set skip_tests_osx = skip_tests_osx + " or test_trainer" %}  # [osx]
# # E OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files
{% set skip_tests_osx = skip_tests_osx + " or test_load_with_safetensors or test_train_stsb or test_model_card_base or test_model_card_data" %}  # [osx]
# # TypeError: MPS BFloat16 is only supported on MacOS 14 or newer
{% set skip_tests_osx = skip_tests_osx + " or test_bfloat16" %}  # [osx]
# E ValueError: The `router_mapping` argument must be a dictionary mapping dataset column names to Router routes, like 'query' or 'document'. A stringified dictionary also works.
{% set skip_tests_linux = "test_hf_argument_parser" %}  # [linux]
{% set skip_tests_linux = skip_tests_linux + " or test_hf_argument_parser_incorrect_string_arguments" %}  # [linux]
{% set skip_tests_linux = skip_tests_linux + " or test_incorrect_string_arguments" %}  # [linux]
# E             comparison failed
# E             Obtained: 0.5718795657157898
# E             Expected: 0.5718804597854614 ± 5.7e-07
{% set skip_tests_linux = skip_tests_linux + " or test_cmnrl_same_grad" %}  # [linux]
{% set ignore_tests = "" %}
# Missing timm/torchvision for newer pythons
{% set ignore_tests = "--ignore=tests/test_custom_models.py" %}
# RuntimeError: isin_Tensor_Tensor_out only works on floating types on MPS for pre MacOS_14_0
{% set ignore_tests = ignore_tests + " --ignore=tests/util/test_hard_negatives.py" %}  # [osx]

test:
  source_files:
    - tests
    - examples
  imports:
    - sentence_transformers
    - sentence_transformers.backend
    - sentence_transformers.backend.utils
    - sentence_transformers.cross_encoder
    - sentence_transformers.data_collator
    - sentence_transformers.datasets
    - sentence_transformers.evaluation
    - sentence_transformers.LoggingHandler
    - sentence_transformers.losses
    - sentence_transformers.model_card
    - sentence_transformers.models
    - sentence_transformers.models.tokenizer
    - sentence_transformers.quantization
    - sentence_transformers.readers
    - sentence_transformers.sampler
    - sentence_transformers.SentenceTransformer
    - sentence_transformers.similarity_functions
    - sentence_transformers.sparse_encoder
    - sentence_transformers.trainer
    - sentence_transformers.training_args
    - sentence_transformers.util
  requires:
    - pip
    - pytest
    - datasets
    - pillow
    # ImportError: Using the `Trainer` with `PyTorch` requires `accelerate>=0.26.0`
    - huggingface_accelerate >=0.26.0
    - einops
  commands:
    - pip check
    - pytest -v -m "not slow" tests {{ ignore_tests }}  # [win]
    - pytest -v -m "not slow" tests {{ ignore_tests }} -k "not ({{ skip_tests_linux }})" # [linux]
    - export PYTORCH_ENABLE_MPS_FALLBACK=1  # [osx]
    - pytest -v -m "not slow" tests {{ ignore_tests }} -k "not ({{ skip_tests_osx }})" # [osx]

about:
  home: https://www.sbert.net
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Sentence Embeddings using BERT / RoBERTa / XLNet
  description: |
    This framework provides an easy method to compute dense vector representations for sentences, 
    paragraphs, and images. The models are based on transformer networks like 
    BERT / RoBERTa / XLM-RoBERTa etc. and achieve state-of-the-art performance in various task. 
    Text is embedding in vector space such that similar text is close and can efficiently be 
    found using cosine similarity.
  doc_url: https://github.com/huggingface/sentence-transformers/blob/main/README.md
  dev_url: https://github.com/UKPLab/sentence-transformers

extra:
  recipe-maintainers:
    - rluria14
    - oblute
    - ndmaxar
