{% set name = "sentence-transformers" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 492eae8e9973f2b758d66d74325661e2816f0b6637365554a1eca9bcf60088ed

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - nltk
    - numpy
    - python >=3.6
    - scikit-learn
    - scipy
    - pytorch >=1.0.1
    - tqdm
    - transformers >=3.1

test:
  imports:
    - sentence_transformers
    - sentence_transformers.datasets
    - sentence_transformers.evaluation
    - sentence_transformers.losses
    - sentence_transformers.models
    - sentence_transformers.models.tokenizer
    - sentence_transformers.readers

about:
  home: https://github.com/UKPLab/sentence-transformers
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Sentence Embeddings using BERT / RoBERTa / XLNet
  doc_url: https://pypi.org/project/sentence-transformers/
  dev_url: https://github.com/UKPLab/sentence-transformers

extra:
  recipe-maintainers:
    - rluria14
    - oblute
    - ndmaxar
