{% set name = "sentence-transformers" %}
{% set version = "2.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dbc60163b27de21076c9a30d24b5b7b6fa05141d68cf2553fa9a77bf79a29136

build:
  # skip s390x and ppc64le because torchvision does not support these
  skip: True  # [linux and (ppc64le or s390x)]
  skip: True  # [py<36]
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - wheel
    - setuptools
  run:
    - nltk
    - numpy  # [not (linux and x86_64)]
    - numpy >=1.22  # [linux and x86_64]
    - python
    - scikit-learn
    - scipy
    - pytorch >=1.6.0
    - torchvision
    - tqdm
    - transformers >=4.6.0,<5.0.0
    - sentencepiece
    - huggingface_hub >=0.4.0

test:
  imports:
    - sentence_transformers
    - sentence_transformers.datasets
    - sentence_transformers.evaluation
    - sentence_transformers.losses
    - sentence_transformers.models
    - sentence_transformers.models.tokenizer
    - sentence_transformers.readers
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/UKPLab/sentence-transformers
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Sentence Embeddings using BERT / RoBERTa / XLNet
  description: |
    This framework provides an easy method to compute dense vector representations for sentences, 
    paragraphs, and images. The models are based on transformer networks like 
    BERT / RoBERTa / XLM-RoBERTa etc. and achieve state-of-the-art performance in various task. 
    Text is embedding in vector space such that similar text is close and can efficiently be 
    found using cosine similarity.
  doc_url: https://pypi.org/project/sentence-transformers/
  dev_url: https://github.com/UKPLab/sentence-transformers

extra:
  recipe-maintainers:
    - rluria14
    - oblute
    - ndmaxar
