{% set name = "sentence-transformers" %}
{% set version = "2.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 492eae8e9973f2b758d66d74325661e2816f0b6637365554a1eca9bcf60088ed

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vvv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - pip
    - python
  run:
    - nltk
    - numpy
    - python
    - scikit-learn
    - scipy
    - pytorch >=1.6.0
    - torchvision
    - tqdm
    - transformers >=4.6.0,<5.0.0
    - sentencepiece
    - huggingface_hub >=0.4.0

test:
  imports:
    - sentence_transformers
    - sentence_transformers.datasets
    - sentence_transformers.evaluation
    - sentence_transformers.losses
    - sentence_transformers.models
    - sentence_transformers.models.tokenizer
    - sentence_transformers.readers

about:
  home: https://github.com/UKPLab/sentence-transformers
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Sentence Embeddings using BERT / RoBERTa / XLNet
  description: |
    This framework provides an easy method to compute dense vector representations for sentences, 
    paragraphs, and images. The models are based on transformer networks like 
    BERT / RoBERTa / XLM-RoBERTa etc. and achieve state-of-the-art performance in various task. 
    Text is embedding in vector space such that similar text is close and can efficiently be 
    found using cosine similarity.
  doc_url: https://pypi.org/project/sentence-transformers/
  dev_url: https://github.com/UKPLab/sentence-transformers

extra:
  recipe-maintainers:
    - rluria14
    - oblute
    - ndmaxar
